let leads=JSON.parse(localStorage.getItem("leadsStudio"))||[];const formLead=document.getElementById("formLead"),listaLeads=document.getElementById("listaLeads"),mensagemVazia=document.getElementById("mensagemVazia"),pesquisa=document.getElementById("pesquisa"),filtroStatus=document.getElementById("filtroStatus"),modal=document.getElementById("modal"),nomeModal=document.getElementById("nomeModal"),mensagemModal=document.getElementById("mensagemModal"),btnWhatsApp=document.getElementById("btnWhatsApp");let leadSelecionado=null;
function salvarLeads(){localStorage.setItem("leadsStudio",JSON.stringify(leads))}
formLead.addEventListener("submit",e=>{e.preventDefault();const nome=document.getElementById("nome").value.trim(),telefone=document.getElementById("telefone").value.trim(),oferta=document.getElementById("oferta").value.trim();if(!nome||!telefone||!oferta)return alert("Preencha todos os campos.");leads.push({id:Date.now(),nome,telefone,oferta,status:"novo"});salvarLeads();formLead.reset();document.getElementById("oferta").value=`Oi, {nome}! Tudo bem? 🤍

Sou a Karine, do Studio. Estou com alguns horários disponíveis para novas clientes este mês e queria te apresentar meu trabalho.

Se tiver interesse, posso te passar os horários disponíveis. ✨`;renderizarLeads()});
function renderizarLeads(){const q=pesquisa.value.toLowerCase().trim(),st=filtroStatus.value,filtrados=leads.filter(l=>(l.nome.toLowerCase().includes(q)||l.telefone.includes(q))&&(st==="todos"||l.status===st));listaLeads.innerHTML="";mensagemVazia.style.display=filtrados.length?"none":"block";filtrados.forEach(l=>{const d=document.createElement("div");d.className="lead";d.innerHTML=`<div class="lead-info"><div class="avatar">${escaparHTML(l.nome.charAt(0).toUpperCase())}</div><div><h3>${escaparHTML(l.nome)}</h3><div class="telefone">${escaparHTML(l.telefone)}</div></div></div><div class="acoes"><select class="status" onchange="alterarStatus(${l.id},this.value)"><option value="novo" ${l.status==="novo"?"selected":""}>Novo</option><option value="contatado" ${l.status==="contatado"?"selected":""}>Contatado</option><option value="respondeu" ${l.status==="respondeu"?"selected":""}>Respondeu</option><option value="agendou" ${l.status==="agendou"?"selected":""}>Agendou</option></select><button class="btn-enviar" onclick="abrirWhatsApp(${l.id})">💬 Enviar</button><button class="btn-excluir" onclick="excluirLead(${l.id})">🗑</button></div>`;listaLeads.appendChild(d)});atualizarCards()}
function atualizarCards(){document.getElementById("totalLeads").textContent=leads.length;document.getElementById("totalContatados").textContent=leads.filter(l=>l.status==="contatado").length;document.getElementById("totalResponderam").textContent=leads.filter(l=>l.status==="respondeu").length;document.getElementById("totalAgendaram").textContent=leads.filter(l=>l.status==="agendou").length}
function alterarStatus(id,status){const l=leads.find(x=>x.id===id);if(!l)return;l.status=status;salvarLeads();renderizarLeads()}
function excluirLead(id){const l=leads.find(x=>x.id===id);if(!l)return;if(confirm(`Deseja excluir o lead ${l.nome}?`)){leads=leads.filter(x=>x.id!==id);salvarLeads();renderizarLeads()}}
function abrirWhatsApp(id){const l=leads.find(x=>x.id===id);if(!l)return;leadSelecionado=l;nomeModal.textContent=`Para: ${l.nome}`;mensagemModal.value=l.oferta.replace(/\{nome\}/gi,l.nome.split(" ")[0]);modal.classList.add("ativo")}
function fecharModal(){modal.classList.remove("ativo");leadSelecionado=null}
btnWhatsApp.addEventListener("click",()=>{if(!leadSelecionado)return;let tel=leadSelecionado.telefone.replace(/\D/g,"");if(tel.length===10||tel.length===11)tel="55"+tel;const msg=mensagemModal.value.trim();if(!msg)return alert("Digite uma mensagem.");leadSelecionado.status="contatado";salvarLeads();renderizarLeads();window.open(`https://wa.me/${tel}?text=${encodeURIComponent(msg)}`,"_blank");fecharModal()});
pesquisa.addEventListener("input",renderizarLeads);filtroStatus.addEventListener("change",renderizarLeads);modal.addEventListener("click",e=>{if(e.target===modal)fecharModal()});function escaparHTML(t){const d=document.createElement("div");d.textContent=t;return d.innerHTML}renderizarLeads();
